# Generated by Django 2.1.7 on 2019-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_db', models.IntegerField(max_length=3)),
                ('destination_db', models.CharField(max_length=20)),
                ('destinationCode_db', models.CharField(max_length=5)),
                ('destinationName_db', models.CharField(max_length=30)),
                ('group_db', models.IntegerField(max_length=5)),
                ('line_db', models.CharField(max_length=10)),
                ('locationCode_db', models.CharField(default='D05', max_length=5)),
                ('locationName_db', models.CharField(default='Capitol South', max_length=30)),
                ('min_db', models.IntegerField(max_length=3)),
            ],
        ),
    ]
